# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96221d942319baa5b4e8849390eec1c1e72c05bc2d41daa33a0e4101fefe2edeb417b709ba80c6dd945905894eb57f533c5cc1e391b67088a420152783095ca9

test:
  secret_key_base: bb586eab0d1322415f330c53c62c5b6b6eb23954841f86e120610318a82ae2ef06901e86b80331235ede25f45024475371b3ac78ce72dd7261650a1184dc88c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
